version: "3.9"
services:
  postgresql:
    image: "postgres:14.1"
    ports:
    - "6080:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2201  
      POSTGRES_DB: users

  registration:
    ports:
      - "8033:8033"
    build:
      context: .
    volumes:
      - ./cmd:/cmd
      
  # db-migrations:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.db-migrations
  #   volumes:
  #     - ./migrations:/migrations
  #   depends_on:
  #     - postgresql
