CREATE TABLE IF NOT EXISTS users_data (
	id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	fname VARCHAR ( 255 ) NOT NULL,
	lname VARCHAR ( 255 ) NOT NULL,
	email VARCHAR ( 255 ) UNIQUE NOT NULL
);



